/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SeriesIndexRouteImport } from './routes/series/index'
import { Route as CategoriesIndexRouteImport } from './routes/categories/index'
import { Route as BooksIndexRouteImport } from './routes/books/index'
import { Route as AuthorsIndexRouteImport } from './routes/authors/index'
import { Route as CategoriesCategoryIdRouteImport } from './routes/categories/$categoryId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesIndexRoute = SeriesIndexRouteImport.update({
  id: '/series/',
  path: '/series/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksIndexRoute = BooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsIndexRoute = AuthorsIndexRouteImport.update({
  id: '/authors/',
  path: '/authors/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesCategoryIdRoute = CategoriesCategoryIdRouteImport.update({
  id: '/categories/$categoryId',
  path: '/categories/$categoryId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categories/$categoryId': typeof CategoriesCategoryIdRoute
  '/authors': typeof AuthorsIndexRoute
  '/books': typeof BooksIndexRoute
  '/categories': typeof CategoriesIndexRoute
  '/series': typeof SeriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categories/$categoryId': typeof CategoriesCategoryIdRoute
  '/authors': typeof AuthorsIndexRoute
  '/books': typeof BooksIndexRoute
  '/categories': typeof CategoriesIndexRoute
  '/series': typeof SeriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/categories/$categoryId': typeof CategoriesCategoryIdRoute
  '/authors/': typeof AuthorsIndexRoute
  '/books/': typeof BooksIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/series/': typeof SeriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/categories/$categoryId'
    | '/authors'
    | '/books'
    | '/categories'
    | '/series'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/categories/$categoryId'
    | '/authors'
    | '/books'
    | '/categories'
    | '/series'
  id:
    | '__root__'
    | '/'
    | '/categories/$categoryId'
    | '/authors/'
    | '/books/'
    | '/categories/'
    | '/series/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoriesCategoryIdRoute: typeof CategoriesCategoryIdRoute
  AuthorsIndexRoute: typeof AuthorsIndexRoute
  BooksIndexRoute: typeof BooksIndexRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
  SeriesIndexRoute: typeof SeriesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/': {
      id: '/series/'
      path: '/series'
      fullPath: '/series'
      preLoaderRoute: typeof SeriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/': {
      id: '/books/'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors/': {
      id: '/authors/'
      path: '/authors'
      fullPath: '/authors'
      preLoaderRoute: typeof AuthorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$categoryId': {
      id: '/categories/$categoryId'
      path: '/categories/$categoryId'
      fullPath: '/categories/$categoryId'
      preLoaderRoute: typeof CategoriesCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriesCategoryIdRoute: CategoriesCategoryIdRoute,
  AuthorsIndexRoute: AuthorsIndexRoute,
  BooksIndexRoute: BooksIndexRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
  SeriesIndexRoute: SeriesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
