/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AuthenticatedSeriesIndexRouteImport } from './routes/_authenticated/series/index'
import { Route as AuthenticatedBooksIndexRouteImport } from './routes/_authenticated/books/index'
import { Route as AuthenticatedAuthorsIndexRouteImport } from './routes/_authenticated/authors/index'
import { Route as AuthenticatedBooksBookIdRouteImport } from './routes/_authenticated/books/$bookId'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSeriesIndexRoute =
  AuthenticatedSeriesIndexRouteImport.update({
    id: '/series/',
    path: '/series/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBooksIndexRoute = AuthenticatedBooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuthorsIndexRoute =
  AuthenticatedAuthorsIndexRouteImport.update({
    id: '/authors/',
    path: '/authors/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBooksBookIdRoute =
  AuthenticatedBooksBookIdRouteImport.update({
    id: '/books/$bookId',
    path: '/books/$bookId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginIndexRoute
  '/books/$bookId': typeof AuthenticatedBooksBookIdRoute
  '/authors': typeof AuthenticatedAuthorsIndexRoute
  '/books': typeof AuthenticatedBooksIndexRoute
  '/series': typeof AuthenticatedSeriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginIndexRoute
  '/books/$bookId': typeof AuthenticatedBooksBookIdRoute
  '/authors': typeof AuthenticatedAuthorsIndexRoute
  '/books': typeof AuthenticatedBooksIndexRoute
  '/series': typeof AuthenticatedSeriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/_authenticated/books/$bookId': typeof AuthenticatedBooksBookIdRoute
  '/_authenticated/authors/': typeof AuthenticatedAuthorsIndexRoute
  '/_authenticated/books/': typeof AuthenticatedBooksIndexRoute
  '/_authenticated/series/': typeof AuthenticatedSeriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/books/$bookId'
    | '/authors'
    | '/books'
    | '/series'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/books/$bookId' | '/authors' | '/books' | '/series'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login/'
    | '/_authenticated/books/$bookId'
    | '/_authenticated/authors/'
    | '/_authenticated/books/'
    | '/_authenticated/series/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/series/': {
      id: '/_authenticated/series/'
      path: '/series'
      fullPath: '/series'
      preLoaderRoute: typeof AuthenticatedSeriesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/books/': {
      id: '/_authenticated/books/'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof AuthenticatedBooksIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/authors/': {
      id: '/_authenticated/authors/'
      path: '/authors'
      fullPath: '/authors'
      preLoaderRoute: typeof AuthenticatedAuthorsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/books/$bookId': {
      id: '/_authenticated/books/$bookId'
      path: '/books/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof AuthenticatedBooksBookIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedBooksBookIdRoute: typeof AuthenticatedBooksBookIdRoute
  AuthenticatedAuthorsIndexRoute: typeof AuthenticatedAuthorsIndexRoute
  AuthenticatedBooksIndexRoute: typeof AuthenticatedBooksIndexRoute
  AuthenticatedSeriesIndexRoute: typeof AuthenticatedSeriesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBooksBookIdRoute: AuthenticatedBooksBookIdRoute,
  AuthenticatedAuthorsIndexRoute: AuthenticatedAuthorsIndexRoute,
  AuthenticatedBooksIndexRoute: AuthenticatedBooksIndexRoute,
  AuthenticatedSeriesIndexRoute: AuthenticatedSeriesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
